version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
      - name: customers

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        freshness:
          warn_after: {count: 1, period: hour }
          error_after: {count: 24, period: hour }
        loaded_at_field: _batched_at
        columns:
          - name: paymentmethod
            tests:
              - accepted_values: 
                  values:
                    - 'credit_card'
                    - 'coupon'
                    - 'bank_transfer'
                    - 'gift_card'